#################################################
# web/db-common.sh
#
# Shared bits for the database backup jobs. Sourced by db-backup.sh /
# db-restore.sh / db-list.sh, never run on its own.
#################################################

. "$(dirname "$(readlink -f "$0")")/sf-common.sh"

BASED="$SF_WEB"
ROOT="$SF_REPO"
BACKUP_DIR="$BASED/db-backups"
LIST_JSON="$BASED/db-backups.json"

# Backup file names are generated by db-backup.sh; anything else is refused
# before it can reach scp or the filesystem.
valid_name(){
	case "$1" in
		litegapps-db-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].lgdb) return 0 ;;
		*) return 1 ;;
	esac
}

# Remote listing -> web/db-backups.json  (name + size, newest first)
write_list(){
	need_sf
	print "- Listing $SF_DB on $SF_HOST"
	RAW="$(rsync -r --list-only -e "ssh $SSH_OPTS" "$SF_USER@$SF_HOST:$SF_DB/" 2>/dev/null)"
	{
		printf '{\n  "generated": "%s",\n  "remote": [\n' "$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
		FIRST=1
		# rsync --list-only prints: <perms> <size> <date> <time> <path>
		printf '%s\n' "$RAW" | awk 'NF>=5 && $1 !~ /^d/ { gsub(",","",$2); print $5, $2 }' |
			grep -E '^litegapps-db-[0-9]{8}-[0-9]{6}\.lgdb ' | sort -r |
			while read -r NAME SIZE; do
				[ $FIRST -eq 1 ] || printf ',\n'
				FIRST=0
				printf '    {"name": "%s", "size": %s}' "$NAME" "$SIZE"
			done
		printf '\n  ]\n}\n'
	} > "$LIST_JSON"
	print "- Wrote $LIST_JSON"
}
